[General]

#enable statistics recording for the application
*.node[*].appl.*.scalar-recording = true
*.node[*].appl.*.vector-recording = true

**.appl.posy.result-recording-modes = -
**.appl.relativeSpeed.result-recording-modes = -
**.appl.controllerAcceleration.result-recording-modes = -


*.node[*].appl.enableLogging = false
*.node[*].appl.prediction = default
*.node[*].appl.aidaId = default
*.node[*].appl.radar = false
*.node[*].appl.model_path = "./NNtraining/training/lstmModel.keras"
*.node[*].appl.scaler_path = "./NNtraining/training/stdScaler.pkl"
*.node[*].appl.window_style = "sliding"

repeat = 100

**.traffic_type = "MisbeTrafficManager"
*.traffic.timeMisbehavior = uniform(15.0,30.0)

*.manager.collisionOutput = "collision.xml"

*.manager.command = "sumo-gui"

include ./commons.ini

*.node[*].appl.defenseEnabled = "${defense = nodef, heuadv, NNdef, full, drd}"
*.node[*].appl.MCdropRep = ${MCdropRep = 3}
*.node[*].appl.MCdropCU = ${MCdropCU = 0.1}

[Config PreMisbeSin]
*.node[*].appl_type = "DefenseApp"
*.node[*].scenario.leaderOscillationFrequency = 0.1 Hz
*.node[*].scenario.oscillationAmplitude = 5 kmph
*.node[*].scenario.startOscillating = 5 s

[Config Misbe]
extends=PreMisbeSin
*.node[*].scenario_type = "MisbehaviorScenario"
*.node[*].scenario.misbehavior = "${type = constPos, randomPos, randomOffset, randomSpeed, randomOffsetSpeed, eventualStop, disruptive, dataReplay}"

[Config Misbehavior4]
extends = Misbe

**.traffic.nCars = 4
**.traffic.platoonSize = 4

*.node[*].scenario.platoonSize = 4
*.node[*].scenario.idMisbehavior = ${id = 0, 1, 2}

*.manager.outputPrefix = "${resultdir}/Misbehavior4_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}_"
output-vector-file = ${resultdir}/Misbehavior4_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}.vec
output-scalar-file = ${resultdir}/Misbehavior4_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}.sca

[Config Misbehavior4NoGui]
extends = Misbehavior4,NoGui


[Config Misbehavior8]
extends = Misbe

#modify for 8 cars
**.traffic.nCars = 8
**.traffic.platoonSize = 8

*.node[*].scenario.platoonSize = 8
*.node[*].scenario.idMisbehavior = ${id = 0, 1, 2, 3, 4, 5, 6}

*.manager.outputPrefix = "${resultdir}/Misbehavior8_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}_"
output-vector-file = ${resultdir}/Misbehavior8_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}.vec
output-scalar-file = ${resultdir}/Misbehavior8_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}.sca


[Config Misbehavior8NoGui]
extends = Misbehavior8,NoGui


[Config Misbehavior16]
extends = Misbe

**.traffic.nCars = 16
**.traffic.platoonSize = 16

*.node[*].scenario.platoonSize = 16
*.node[*].scenario.idMisbehavior = ${id = 0, 7}

*.manager.outputPrefix = "${resultdir}/Misbehavior16_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}_"
output-vector-file = ${resultdir}/Misbehavior16_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}.vec
output-scalar-file = ${resultdir}/Misbehavior16_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}.sca


[Config Misbehavior16NoGui]
extends = Misbehavior16,NoGui


[Config TrafficAround]
extends=PreMisbeSin
*.node[4..12].appl.defenseEnabled = "nodef"


**.traffic_type = "MisbeNoisyTrafficManager"
**.traffic.nCars = 4
**.traffic.platoonSize = 4
**.traffic.trafficNoiseAround = true
**.traffic.numNoisyVehicles = 9
*.traffic.timeMisbehavior = uniform(15.0, 30.0)

*.node[0..3].scenario_type = "MisbehaviorScenario"
*.node[4..12].scenario_type = "NoisyScenario"

*.node[*].scenario.platoonSize = 4
# platoonInsertSpeed +- oscillationAmplitude
*.node[*].scenario.noisyCarSpeed = uniform(${leaderSpeed}-2.5kmph, ${leaderSpeed}+2.5kmph)
*.node[*].scenario.numNoisyVehicles = 9


[Config TrafficAroundNoisyMisb]
extends=TrafficAround

*.node[0..3].scenario.misbehavior = "none"
*.node[0..3].scenario.idMisbehavior = -1

*.node[4..12].scenario.idNoisyAttacker = ${noisyid = 4, 5, 6, 7, 8, 9, 10, 11, 12}
*.node[4..12].scenario.misbehavior = "${misbType = disruptive, dataReplay}"

*.manager.outputPrefix = "${resultdir}/TrafficAroundNoisyMisb_${defense}_${misbType}_${noisyid}_${MCdropRep}_${MCdropCU}_${repetition}_"
output-vector-file = ${resultdir}/TrafficAroundNoisyMisb_${defense}_${misbType}_${noisyid}_${MCdropRep}_${MCdropCU}_${repetition}.vec
output-scalar-file = ${resultdir}/TrafficAroundNoisyMisb_${defense}_${misbType}_${noisyid}_${MCdropRep}_${MCdropCU}_${repetition}.sca

[Config TrafficAroundNoisyMisbNoGui]
extends = TrafficAroundNoisyMisb,NoGui


[Config TrafficAroundPlatoonMisb]
extends=TrafficAround

*.node[0..3].scenario.misbehavior = "${type = constPos, randomPos, randomOffset, randomSpeed, randomOffsetSpeed, eventualStop, disruptive, dataReplay}"
*.node[0..3].scenario.idMisbehavior = ${id = 0, 1, 2}

*.node[4..12].scenario.idNoisyAttacker = -1
*.node[4..12].scenario.misbehavior = "none"

*.manager.outputPrefix = "${resultdir}/TrafficAroundPlatoonMisb_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}_"
output-vector-file = ${resultdir}/TrafficAroundPlatoonMisb_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}.vec
output-scalar-file = ${resultdir}/TrafficAroundPlatoonMisb_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}.sca

[Config TrafficAroundPlatoonMisbNoGui]
extends = TrafficAroundPlatoonMisb,NoGui


[Config Misbehavior4DRD]
extends = PreMisbeSin
*.node[*].scenario_type = "MisbehaviorScenario"
*.node[*].scenario.misbehavior = "${type = disruptive, dataReplay}"

**.traffic.nCars = 4
**.traffic.platoonSize = 4

*.node[*].scenario.platoonSize = 4
*.node[*].scenario.idMisbehavior = ${id = 0, 1, 2}

*.manager.outputPrefix = "${resultdir}/Misbehavior4DRD_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}_"
output-vector-file = ${resultdir}/Misbehavior4DRD_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}.vec
output-scalar-file = ${resultdir}/Misbehavior4DRD_${defense}_${type}_${id}_${MCdropRep}_${MCdropCU}_${repetition}.sca

[Config Misbehavior4DRDNoGui]
extends = Misbehavior4DRD,NoGui
